### ISSUE TITLE
Small problem with configured arrow keys in the RA core

### ISSUE THREAD

**Issue by i30817** [AZO234/NP2kai#31]
Now i'm having trouble having the down key i registered for retroarch to work with this emulator... 

It moves slightly down, then stops and moves up again...

which is not surprising considering my 'down' is the 'up arrow' in the keypad key (there is a method to this madness, it's to concentrate all the multiple axis on the same hand - and my normal arrow keys are broken).

What i'm surprised is that the core doesn't override 'sent keys' to the emulator if the keys being used are both a 'normal' keyboard shortcut and retropad binding. I'd expect that the RA pad binding wins everytime and the key gets 'consumed'.

I haven't seen this behavior in other cores live moving the cursor in the scummvm menu or even on px68 core in games (i tested Final Fight x68000, thou i suppose this can be because the game doesn't use the keypad arrow keys).

gamefocus or numlock doesn't matter for this problem. It can be tested by starting 'Steam Hearts' and checking the main menu. 

If you set the:
retropad up key to ' / ' in keypad
retropad down key to ' 8 ' in keypad

you can't go down the options more than 1 time, to the '2 players' setting. You can't go further down to the 'options' setting, and in gameplay, you can't move down (or rather you do, but immediately go up and get 'stuck' on the original position).

Cheers.

**Comment by AZO234** [comment]
I'm sorry for replying late.  
Because I am difficult to understand English. It is my own 'bug'.

The problem is,
* Steam Hearts recognizes '8' key as up.
* NP2 recognizes '8 key down'. (NP2 RA ver recognize 'key down' instead of 'key code'.)
* RA issues the 'key code of the down arrow key'.

It is a big mess.
I'll try to change NP2 key recognizes with RA's key code.

Cheers.

**Comment by i30817** [comment]
Thanks. Yeah the idea i had is 'RA keycode for key always wins and prevents the emulator from reacting to the 'real' keycode', sort of like a override.

**Comment by AZO234** [comment]
I checked.
'Keypad8' Keycode was sended from RA.
And 'Joypad down' also was sended.

Because NP2 core is PC-98 computer emulation have keyboard (and Joypads),
I can't disable keyboard(and Joypads) input.

Accordingly, we can't 'Down' with Keypad8 key on games use 'Keypad key and support Joypads'.

Please understand.

**Comment by i30817** [comment]
Maybe i should ask for this on the RA github itself actually.
